export const carousels = [
  {
    path: '/bebes/carousel1/',
    images: [
      '1.webp',
      '2.webp',
      '3.webp',
      '4.webp',
      '5.webp',
      '6.webp',
      '7.webp',
      '8.webp',
      '9.webp',
      '10.webp',
      '11.webp',
      '12.webp',
      '13.webp',
      '14.webp',
      '15.webp',
      '16.webp',
      '17.webp',
      '18.webp',
      '19.webp',
      '20.webp',
      '21.webp',
      '22.webp',
      '23.webp',
      '24.webp',
      '25.webp',
      '26.webp',
      '27.webp',
      '28.webp',
      '29.webp',
      '30.webp',
      '31.webp',
      '32.webp',
      '33.webp',
    ],
    title: 'Estudio',
    text: 'Reportajes de corta duración, en estudio, creativas y diferentes, vestuario incluido. Incluye 12 fotografías editadas, en alta calidad en entrega digital.',
  },
  {
    path: '/bebes/carousel2/',
    images: [
      '1.webp',
      '2.webp',
      '3.webp',
      '4.webp',
      '5.webp',
      '6.webp',
      '7.webp',
      '8.webp',
      '9.webp',
      '10.webp',
      '11.webp',
      '12.webp',
      '13.webp',
    ],
    title: 'Exteriores',
    text: 'Reportajes al atardecer en localizaciones que te definan, junto a tu pareja, a tu familia y vestuario incluido. Incluye 30 fotografías editadas, en alta calidad en entrega digital.',
  },
  {
    path: '/bebes/carousel3/',
    images: [
      '1.webp',
      '2.webp',
      '3.webp',
      '4.webp',
      '5.webp',
      '6.webp',
      '7.webp',
      '8.webp',
      '9.webp',
      '10.webp',
      '11.webp',
      '12.webp',
      '13.webp',
      '14.webp',
      '15.webp',
    ],
    title: 'Embarazo + Bebé',
    text: 'Llévate las 12/30 fotos del embarazo impresas en 2 pliegos extra en el álbum de tu bebé al contratar los dos reportajes de forma gratuita.',
  },
]
