export const carousels = [
  {
    path: '/embarazo/carousel1/',
    images: [
      '1.webp',
      '2.webp',
      '3.webp',
      '4.webp',
      '5.jpg',
      '6.webp',
      '7.jpg',
      '8.webp',
      '9.webp',
      '10.jpg',
      '11.jpg',
      '12.jpg',
      '13.jpg',
      '14.jpg',
      '15.jpg',
      '16.jpg',
      '17.webp',
      '18.jpg',
    ],
    title: 'Estudio',
    text: 'Reportajes de corta duración, en estudio, creativas y diferentes, vestuario incluido. Incluye 12 fotografías editadas, en alta calidad en entrega digital.',
  },
  {
    path: '/embarazo/carousel2/',
    images: [
      '1.jpg',
      '2.webp',
      '3.webp',
      '4.webp',
      '5.webp',
      '6.webp',
      '7.webp',
      '8.webp',
    ],
    title: 'Exteriores',
    text: 'Reportajes al atardecer en localizaciones que te definan, junto a tu pareja, a tu familia y vestuario incluido. Incluye 30 fotografías editadas, en alta calidad en entrega digital.',
  },
  {
    path: '/embarazo/carousel3/',
    images: [
      '1.jpg',
    ],
    title: 'Embarazo + Bebé',
    text: 'Llévate las 12/30 fotos del embarazo impresas en 2 pliegos extra en el álbum de tu bebé al contratar los dos reportajes de forma gratuita.',
  },
]
